using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.OleDb;
using dbTurnos;


namespace dbTurnos.DataSQL
{
    /// <summary>DataTable que se cargar con lo datos obtenidos a partir de una sentencia SQL.</summary>
    public class AutoGeneratedDataTable : DataTable
    {
        private static string _cadenaConexion = "";
        public static string CadenaConexion { get { return _cadenaConexion; } set { _cadenaConexion = value; } }
        private string _consulta;
        public string ConsultaSQL { get { return _consulta; } set { _consulta = value; } }//HACK: refinar Objeto. lo dejo?

        /// <summary>Crea una instancia de AutoGeneratedDataTable, con los datos especificados por la sentencia SQL.</summary>
        /// <exception cref="System.InvalidOperationException">Puede ocurrir al abrir la conexion con, o al intentar extraer los datos de la BD.</exception>
        /// <exception cref="System.Data.OleDb.OleDbException">Solo puede ocurrir al abrir la conexion con la DB.</exception>
        /// <exception cref="dbTurnos.DataSQL.CadenaDeConexionNoDefinida">Ocurre al intentar instanciar un objeto de esta clase sin previamente definir la propiedad CadenaDeConexión.</exception>
        public AutoGeneratedDataTable(string consulta)
            : base()
        {
            _consulta = consulta;
            Refrescar();
        }
        /// <summary>ACtualiza los datos del DataTable segun la Base de Datos.</summary>
        /// <exception cref="System.InvalidOperationException">Puede ocurrir al abrir la conexion con, o al intentar extraer los datos de la BD.</exception>
        /// <exception cref="System.Data.OleDb.OleDbException">Solo puede ocurrir al abrir la conexion con la DB.</exception>
        public void Refrescar()
        {
            if (CadenaConexion == "")
                throw new CadenaDeConexionNoDefinida();
            using (OleDbConnection conexion = new OleDbConnection (CadenaConexion))
            {
                 OleDbCommand comandoSql = new OleDbCommand(_consulta, conexion);
                try
                {
                    conexion.Open();
                    OleDbDataAdapter da = new OleDbDataAdapter(comandoSql);
                    Clear();
                    da.Fill(this);
                }
                finally
                {
                    conexion.Close();
                }
            }
        }
    }

    public class CadenaDeConexionNoDefinida : Exception
    {
        public CadenaDeConexionNoDefinida() : base("Se intento instanciar un objeto AutoGeneratedDataTable, sin antes definir la propiedad CadenaDeConexion (a la base de datos).") { }
    }
}
