using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Odbc;


namespace dbTurnos.DataSQL
{
    /// <summary>DataTable que se cargar con lo datos obtenidos a partir de una sentencia SQL.</summary>
    public class AutoGeneratedDataTable : DataTable
    {
        //TODO: extraer cadena conexin para abstraer clase

        private string _consulta;
        public string ConsultaSQL { get { return _consulta; } set { _consulta = value; } }
        public AutoGeneratedDataTable(string consulta)
            : base()
        {
            _consulta = consulta;
            Refrescar();
        }
        public void show()
        {
            new Form2(this).ShowDialog();
        }
        public void Refrescar()
        {
            using (OdbcConnection conexion = new OdbcConnection(new Properties.Settings().Bar_TurnosConnectionString))
            {
                OdbcCommand comandoSql = new OdbcCommand(_consulta, conexion);
                try
                {
                    conexion.Open();
                    OdbcDataAdapter da = new OdbcDataAdapter(comandoSql);
                    this.show();
                    Clear();
                    this.show();
                    da.Fill(this);
                    this.show();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
                finally
                {
                    conexion.Close();
                }
            }
        }
    }
}
