using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using db__Turnos.Excepciones;

namespace db__Turnos
{
    public class FuncionesDb
    {
        //TODO: cifrar cadena conexion.
        //TODO: manejo de excepciones de la bd.

        /// <summary>Devuelve un dataTable con los turnos abiertos en la db.</summary>
        public DataTable getTurnosAbiertos()
        {
            return new AutoGeneratedDataTable("SELECT Usuarios.usuario, Usuarios.nombre, Turnos.fechaInicio FROM Usuarios INNER JOIN Turnos ON Usuarios.id = Turnos.idUsuario WHERE (((Turnos.fechaFin)=Null))");
        }

        /// <summary>Abre un turno para un usuario, con le fecha especifica, siempre cuando no exista uno ya abierto.</summary>
        public void AbrirTurnos(int idUsuario, DateTime inicio)
        {
            //TODO: filtrar campos contra SQL inyection.
            if (new AutoGeneratedDataTable("SELECT Turnos.idUsuario, Turnos.fechaInicio FROM Turnos WHERE ((Turnos.idUsuario = "+idUsuario+") AND (Turnos.fechaFin=Null))").Rows.Count != 0)
                throw new YaTieneTurnoAbiertoException();
            new SQLNoConsulta("INSERT INTO Turnos (idUsuario, fechaInicio) VALUES ('" + idUsuario + "', #" + inicio.ToString("yyyy/MM/dd hh:mm:ss") + "#)").Ejecutar();
            
        }

        /// <summary>Cierra el turno abierto para un usuario especifico.</summary>
        public void CerrarTurno(int idUsuario, DateTime fin)
        {
            //TODO: filtrar campos contra SQL inyection.
            DataTable turnoAbierto = new AutoGeneratedDataTable("SELECT Turnos.idUsuario, Turnos.fechaInicio FROM Turnos WHERE ((Turnos.idUsuario = " + idUsuario + ") AND (Turnos.fechaFin=Null))");
            if (turnoAbierto.Rows.Count == 0)
                throw new NoHayTurnoAbiertoException();
            if (Convert.ToDateTime(turnoAbierto.Rows[0]["fechaInicio"]) > fin)
                throw new InicioTurnoMayorQueFinException();
            new SQLNoConsulta("UPDATE Turnos SET fechaFin = #" + fin.ToString("yyyy/MM/dd hh:mm:ss") + "# WHERE (idUsuario  = '" + idUsuario + "') AND (fechaFin IS NULL)").Ejecutar();
        }

        /// <summary>Cambia la contraseña de un usuario espefcifico.</summary>
        public void CambiarContraseña(int idUsuario, string nuevaContraseña)
        {
            //TODO: cifrar contraseña
            new SQLNoConsulta("UPDATE Usuarios SET Usuarios.contraseñaSHA = "+nuevaContraseña+" WHERE (((Usuarios.id)="+idUsuario+"))");
        }

        /// <summary>Devuelve el id del usuario que coincide con  el par usuario/contraseña.</summary>
        public int Identificar(string usuario, string contraseña)
        {
            DataTable idTable;
            //TODO: cifrar contraseña
            //TODO: filtar caracteres especiales usuario, cifrar contraseña.
            usuario = usuario;
            contraseña = contraseña;

            idTable = new AutoGeneratedDataTable("SELECT TOP 1 Usuarios.id FROM Usuarios WHERE (((Usuarios.usuario)=" + usuario + ") AND ((Usuarios.contraseñaSHA)=" + contraseña + "))");

            return Convert.ToInt32(idTable.Rows[0][0]);
        }

    }
}
